dirs:
  - /tmp/abc
uploader: example
storage:
  provider: cos
  secretId: xxxxxxxxx
  secretKey: xxxxxxxxx
  bucket: xxxxxxxxx
  region: ap-guangzhou
  path: / # 必须以 / 结尾


  # provider: ssh
  # path: /tmp/ # 必须以 / 结尾
  # connect:
  #   host: 1.2.3.4
  #   port: 22
  #   username: root
  #   # password: password
  #   privateKey: /path/id_rsa
  #   passphrase:
